defaults:
  - callbacks: default_callbacks
  - data: default_data
  - logger: wandb_logger
  - trainer: default_trainer
  - model: Baseline
  - _self_

name: foo
predict_filename: foo
checkpoint_path: "/path/to/checkpoint.pt"
